name: "Continuous Integration"

on:
  pull_request:
  pull_request_target:
  push:
    branches:
      - master

jobs:
  ci:
    name: "Run Build"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Run Lint"
        run: make lint

      - name: "Run Tests"
        run: make test
